### PR TITLE
Get basic unit testing and building working.

### PR DESCRIPTION
**Pull request by Besler**

### CODE REVIEW

**Comment by Besler** [comment]
@PayamZandiyeh I converted the repository to a basic module. I haven't integrated all the tests or added the test images yet.

**Comment by Besler** [comment]
Sorry, typically you wait for all the tests to pass!

**Comment by PayamZandiyeh** [comment]
@Besler sounds very good. We can remove the files in the registration in the other repository if we like to continue on this project?

**Comment by PayamZandiyeh** [comment]
@Besler Sorry! I should have asked

**Comment by Besler** [comment]
No problem at all! Just for next time really. Hopefully I did a good job :p

**Comment by Besler** [comment]
Okay cool, looks like all systems are go! @PayamZandiyeh

**Comment by PayamZandiyeh** [comment]
@Besler Perfect! However, I need a bit of tutorial here if you will have time sometimes today/tomorrow/anytime

**Comment by Besler** [comment]
@PayamZandiyeh Yes, for sure. I'm around tomorrow before 11:30 and after 1. Send me an email. Before then, download and compile ITK on your system.

**Comment by PayamZandiyeh** [comment]
@Besler I have everything up and running itk wise.

**Pull request merged**
